default: &default
  adapter:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: seta-rails-api-dev

test:
  <<: *default
  database: seta-rails-api-test

production:
  <<: *default
  database: seta-rails-api-prod
